import os
# JWT CONFIG
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY') or 'extra-secure-key'

# MONGODB CONFIG
MONGO_URI = os.getenv("MONGO_URI")
MONGO_DB_NAME = 'users'
MONGO_DB_COLLECTION_NAME = 'users_data'

# VARIABLES
DEFAULT_WORK_MINUTES = 45
DEFAULT_BREAK_MINUTES = 5
